datasets:
  taxi:
    column_mapping:
      categorical_features:
    
      numerical_features:
        - 'WindSpeed', 'Sunshine', 'AirPressure', 'Radiation', 'AirTemperature', 'RelativeAirHumidity'
    data_format:
      header: true
      separator: ','
    monitors:
      - data_drift
    reference_file: /home/akash/Documents/programming/luminous hackathon ppt/Luminous MLOps/01-intro/Solar Power Plant Data.csv
service:
  calculation_period_sec: 2
  min_reference_size: 30
  moving_reference: false
  datasets_path: datasets
  use_reference: true
  window_size: 5
